import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'fa' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, defaultText?: string) => string;
  isRtl: boolean;
  formatDate: (jalaliStr?: string, gregorianStr?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fa: {
    // General & Common
    'app.title': 'سامانه جامع مدیریت نگهداری و تعمیرات (CMMS)',
    'app.subtitle': 'مدیریت و پایش خطوط، ایستگاه‌ها، پایش وضعیت فنی و روانکاری',
    'common.search': 'جستجو...',
    'common.add': 'افزودن',
    'common.edit': 'ویرایش',
    'common.delete': 'حذف',
    'common.cancel': 'انصراف',
    'common.save': 'ذخیره تغییرات',
    'common.submit': 'ثبت اطلاعات',
    'common.back': 'بازگشت',
    'common.actions': 'عملیات',
    'common.status': 'وضعیت',
    'common.date': 'تاریخ',
    'common.time': 'زمان',
    'common.technician': 'نام تکنسین / کارشناس',
    'common.inspector': 'متولی / کارشناس بازرسی',
    'common.notes': 'توضیحات و یادداشت فنی',
    'common.loading': 'در حال بارگذاری...',
    'common.normal': 'عادی',
    'common.warning': 'هشدار',
    'common.danger': 'خطر / بحرانی',
    'common.acceptable': 'قابل قبول',
    'common.all': 'همه',
    'common.filter': 'فیلتر',
    'common.export_pdf': 'خروجی PDF',
    'common.export_excel': 'خروجی اکسل',
    'common.print': 'پرینت',
    'common.download': 'دانلود',
    'common.upload': 'آپلود',
    'common.confirm': 'تأیید',
    'common.change': 'تغییر',
    'common.close': 'بستن',
    'common.yes': 'بله',
    'common.no': 'خیر',
    'common.yes_delete': 'بله، حذف شود',
    'common.select': 'انتخاب کنید',
    'common.details': 'مشخصات و جزئیات',
    'common.view': 'مشاهده',
    'common.view_new_tab': 'مشاهده در تب جدید',
    'common.remove': 'حذف',
    'common.no_records_found': 'هیچ رکوردی یافت نشد.',
    'common.showing': 'نمایش',
    'common.to': 'تا',
    'common.of': 'از',
    'common.records': 'رکورد',
    'common.previous': 'قبلی',
    'common.next': 'بعدی',
    'common.role': 'نقش کاربری',
    'common.success': 'عملیات با موفقیت انجام شد',
    'common.error': 'خطایی رخ داد',
    'common.server_error': 'خطا در ارتباط با سرور',
    'common.access_denied': 'شما دسترسی مجاز به این صفحه را ندارید.',
    'common.optional': 'اختیاری',
    'common.required': 'الزامی',

    // Navigation & Layout
    'nav.stations_equipments': 'ایستگاه‌ها و تجهیزات',
    'nav.analytics': 'گزارش‌ها',
    'nav.condition_monitoring': 'پایش وضعیت فنی',
    'nav.lubrication': 'پایش روانکاری',
    'nav.downtimes': 'ثبت توقفات',
    'nav.admin_section': 'مدیریت کلان سیستم',
    'nav.users': 'مدیریت کاربران',
    'nav.logs': 'گزارش عملکرد',
    'nav.settings': 'تنظیمات سیستم',
    'nav.profile': 'پروفایل و مشخصات کاربر',
    'nav.logout': 'خروج از حساب',
    'nav.switch_complex_line': 'تغییر مجموعه / خط',

    // Hierarchy & Complex Selection
    'complex.default_portal_title': 'سامانه انتخاب و مدیریت مجموعه‌ها',
    'complex.select_instruction': 'لطفاً مجموعه مورد نظر خود را جهت ورود و پایش تجهیزات انتخاب نمایید.',
    'complex.add_button': 'افزودن مجموعه جدید',
    'complex.name': 'نام مجموعه',
    'complex.location': 'موقعیت / شهر',
    'complex.description': 'توضیحات مجموعه',
    'complex.image_url': 'آدرس تصویر مجموعه',
    'complex.password': 'رمز ورود مجموعه (اختیاری)',
    'complex.enter_password': 'رمز عبور این مجموعه را وارد کنید',
    'complex.lines_count': 'تعداد خطوط',
    'complex.no_complexes': 'هیچ مجموعه‌ای یافت نشد.',
    'complex.edit_complex': 'ویرایش مجموعه',
    'complex.placeholder_name': 'مثال: تله‌کابین توچال / مجموعه تفریحی نمک‌آبرود',
    'complex.placeholder_loc': 'تهران، کیش، رامسر، چالوس...',
    'complex.placeholder_desc': 'توضیحات فنی، مشخصات و کاربری مجموعه...',
    'complex.placeholder_pass': 'رمز عبور دلخواه (در صورت نیاز)...',

    // Line Selection
    'line.add_button': 'افزودن خط جدید',
    'line.name': 'نام خط',
    'line.type': 'نوع خط',
    'line.stations': 'ایستگاه‌ها',
    'line.no_lines': 'هیچ خطی برای این مجموعه ثبت نشده است.',
    'line.placeholder_name': 'مثال: خط ۱ تله‌کابین قله',
    'line.placeholder_type': 'تله‌کابین، تله‌سیژ، واگن کششی...',
    'line.telecabin': 'تله‌کابین',
    'line.telesiege': 'تله‌سیژ',
    'line.funicular': 'فونیکولار / واگن کششی',
    'line.gondola': 'گوندولا (تله‌کابین)',

    // Stations & Equipment Dashboard
    'dashboard.stations_title': 'ایستگاه‌های',
    'dashboard.select_station_hint': 'لطفاً ایستگاه مورد نظر را برای مشاهده تجهیزات انتخاب کنید.',
    'dashboard.add_station': 'افزودن ایستگاه جدید',
    'dashboard.station_name': 'نام ایستگاه',
    'dashboard.station_sequence': 'شماره ترتیب ایستگاه',
    'dashboard.equipments_title': 'تجهیزات ایستگاه',
    'dashboard.add_equipment': 'افزودن تجهیز جدید',
    'dashboard.equipment_name': 'نام تجهیز',
    'dashboard.equipment_code': 'کد تجهیز',
    'dashboard.import_excel': 'ایمپورت اکسل دستورکارها',
    'dashboard.select_standard_for_import': 'انتخاب استاندارد سازنده برای فایل اکسل:',
    'dashboard.standard_bartholet': 'استاندارد بارتولت',
    'dashboard.standard_doppelmayr': 'استاندارد دوپلمایر',
    'dashboard.standard_poma': 'استاندارد پوما',
    'dashboard.standard_general': 'استاندارد عمومی / خودکار',
    'dashboard.standard_given': 'استاندارد داده‌شده / عمومی (ISO / Given Standard)',
    'dashboard.all_standards': 'همه استانداردها',
    'dashboard.no_equipments': 'هیچ تجهیزی برای این ایستگاه ثبت نشده است.',
    'dashboard.excel_modal_desc': 'فایل‌های اکسل بر اساس استانداردهای بارتولت (Bartholet)، دوپلمایر (Doppelmayr)، پوما یا عمومی قابل تفکیک و ورود می‌باشند.',
    'dashboard.excel_select_file': 'فایل اکسل (.xlsx, .xls):',
    'dashboard.import_submit': 'بارگذاری و ورود اطلاعات',
    'dashboard.importing': 'در حال پردازش اکسل...',
    'dashboard.reorder': 'تغییر ترتیب نمایش',

    // Equipment Detail & Tasks
    'equipment.details': 'مشخصات تجهیز',
    'equipment.tasks': 'دستورکارهای نگهداری و بازرسی',
    'equipment.add_task': 'افزودن دستورکار جدید',
    'equipment.task_subject': 'عنوان دستورکار',
    'equipment.task_code': 'کد دستورکار',
    'equipment.task_standard': 'استاندارد مرجع سازنده',
    'equipment.sort_by_standard': 'مرتب‌سازی بر اساس استاندارد:',
    'equipment.frequency': 'دوره تناوب',
    'equipment.last_date': 'آخرین بازرسی',
    'equipment.next_date': 'سررسید بعدی',
    'equipment.instructions': 'دستورالعمل اجرا',
    'equipment.criteria': 'معیار پذیرش',
    'equipment.part_name': 'نام قطعه / بخش',
    'equipment.warning': 'پیام هشدار و نکات ایمنی',
    'equipment.inspect_action': 'ثبت بازرسی',
    'equipment.operating_hours': 'ساعت کارکرد',
    'equipment.inspection_comment': 'نتیجه و توضیحات بازرسی',
    'equipment.status_normal': 'عادی',
    'equipment.status_warning': 'هشدار',
    'equipment.status_broken': 'خراب / نیاز به تعمیر',
    'equipment.freq_daily': 'روزانه',
    'equipment.freq_weekly': 'هفتگی',
    'equipment.freq_monthly': 'ماهانه',
    'equipment.freq_3months': '۳ ماهه',
    'equipment.freq_6months': '۶ ماهه',
    'equipment.freq_annually': 'سالانه',
    'equipment.history': 'تاریخچه بازرسی‌های انجام شده',

    // Downtimes & Management
    'downtime.title': 'ثبت و تحلیل توقفات اضطراری و برنامه‌ریزی‌شده',
    'downtime.subtitle': 'مدیریت ریشه‌ای خرابی‌ها، زمان تعمیر و محاسبه شاخص‌های توقف خط',
    'downtime.add_new': 'ثبت توقف جدید',
    'downtime.equipment': 'تجهیز آسیب‌دیده',
    'downtime.reason': 'علت بروز توقف',
    'downtime.start_time': 'زمان شروع توقف',
    'downtime.duration': 'مدت توقف',
    'downtime.duration_min': 'مدت زمان (دقیقه)',
    'downtime.entire_site': 'کل سایت / ایستگاه',
    'downtime.unknown': 'نامشخص',
    'downtime.delete_title': 'حذف گزارش توقف',
    'downtime.delete_confirm': 'آیا از حذف این گزارش توقف اطمینان دارید؟',
    'downtime.reason_mechanical': 'نقص مکانیکی',
    'downtime.reason_electrical': 'نقص الکتریکی / تابلو فرمان',
    'downtime.reason_weather': 'بدی شرایط جوی و باد شدید',
    'downtime.reason_human': 'خطای انسانی / اپراتوری',
    'downtime.reason_pm': 'تعمیرات پیشگیرانه و سرویس',
    'downtime.reason_other': 'سایر موارد',
    'downtime.modal_title': 'ثبت رکورد جدید توقف',
    'downtime.all_equipment_option': 'توقف کل خط / تمام تجهیزات',

    // Analytics & KPIs
    'analytics.title': 'گزارش‌ها',
    'analytics.subtitle': 'تحلیل آماری نگهداری پیشگیرانه، قابلیت اطمینان و تفکیک توقفات',
    'analytics.total_tasks': 'کل دستورکارهای سال',
    'analytics.reliability': 'نرخ قابلیت اطمینان (تخمینی)',
    'analytics.total_downtimes': 'کل زمان توقفات (دقیقه)',
    'analytics.compliance_title': 'انطباق و پایبندی به دستورکارهای نگهداری',
    'analytics.breakdown_title': 'تفکیک درصد علل ریشه‌ای توقفات',
    'analytics.on_time': 'انجام شده (به موقع)',
    'analytics.delayed': 'انجام شده با تأخیر',
    'analytics.pending': 'معوق / در انتظار انجام',
    'analytics.no_data': 'داده‌ای برای نمایش نمودار وجود ندارد',
    'analytics.generating_pdf': 'در حال تولید فایل PDF...',
    'analytics.export_btn': 'خروجی PDF / پرینت گزارش',

    // Users & Roles
    'users.title': 'مدیریت کاربران و سطوح دسترسی',
    'users.subtitle': 'تعریف نقش‌ها، اختیارات امنیتی و تخصیص کاربران به مجموعه‌ها و خطوط',
    'users.add_user': 'افزودن کاربر جدید',
    'users.full_name': 'نام و نام خانوادگی',
    'users.username': 'نام کاربری',
    'users.password': 'رمز عبور',
    'users.phone': 'شماره تماس',
    'users.position': 'سمت / عنوان شغلی',
    'users.role': 'سطح دسترسی و نقش',
    'users.assigned_complex': 'مجموعه تخصیص‌یافته',
    'users.assigned_line': 'خط تخصیص‌یافته',
    'users.assigned_station': 'ایستگاه تخصیص‌یافته',
    'users.role_super_admin': 'مدیر ارشد کل سیستم',
    'users.role_complex_admin': 'مدیر مجموعه',
    'users.role_line_supervisor': 'سرپرست خط',
    'users.role_station_operator': 'اپراتور ایستگاه',
    'users.role_manager': 'مدیر سیستم',
    'users.role_operator': 'اپراتور فنی',
    'users.delete_confirm': 'آیا از حذف این کاربر اطمینان دارید؟',
    'users.no_users': 'هیچ کاربری ثبت نشده است.',

    // Logs
    'logs.title': 'گزارش عملکرد و لاگ‌های امنیتی',
    'logs.subtitle': 'تاریخچه ورود، خروج، تغییرات و تمامی فعالیت‌های ثبت‌شده در سامانه',
    'logs.user': 'کاربر',
    'logs.action': 'عملیات',
    'logs.details': 'شرح و جزئیات فعالیت',
    'logs.timestamp': 'زمان (تاریخ و ساعت)',
    'logs.loading': 'در حال دریافت لاگ‌ها...',
    'logs.filename': 'گزارش_عملکرد_سیستم',
    'logs.search_placeholder': 'جستجو در نام کاربر، نوع عملیات، جزئیات...',

    // Settings
    'settings.title': 'تنظیمات سیستم و شخصی‌سازی',
    'settings.subtitle': 'مدیریت نام سامانه، مشخصات شرکت و لوگوی اختصاصی',
    'settings.company_name': 'نام سامانه / عنوان شرکت',
    'settings.logo': 'لوگوی سیستم',
    'settings.change_logo': 'تغییر لوگوی شرکت',
    'settings.no_logo': 'بدون لوگو',
    'settings.save_settings': 'ذخیره تنظیمات',
    'settings.saved_success': 'تنظیمات با موفقیت ذخیره و اعمال گردید.',
    'settings.placeholder_company': 'مثال: سامانه جامع CMMS تله‌کابین توچال',

    // Profile
    'profile.title': 'ویرایش پروفایل و اطلاعات کاربری',
    'profile.subtitle': 'مشاهده و به‌روزرسانی مشخصات فردی و رمز عبور حساب کاربری',
    'profile.new_password': 'رمز عبور جدید',
    'profile.new_password_hint': 'تنها در صورت تمایل به تغییر رمز عبور وارد نمایید',
    'profile.senior_manager': 'مدیر ارشد',
    'profile.operator': 'اپراتور سیستم',

    // Login
    'login.title': 'سامانه مدیریت نگهداری و تعمیرات',
    'login.subtitle': 'ورود به پنل کاربری پایش وضعیت و نگهداری پیشگیرانه',
    'login.username': 'نام کاربری',
    'login.password': 'رمز عبور',
    'login.submit': 'ورود به سامانه',
    'login.logging_in': 'در حال اعتبارسنجی...',
    'login.secure_note': 'نسخه امن CMMS • تمامی فعالیت‌ها پایش و ثبت می‌شوند',
    'login.invalid_creds': 'نام کاربری یا رمز عبور اشتباه است.',

    // Condition Monitoring (CM) - Core
    'cm.title': 'سیستم جامع پایش وضعیت فنی',
    'cm.subtitle': 'پوشش ۶ زیردامنه تخصصی پایش: ارتعاشات، ترموگرافی، آنالیز روغن، روانکاری، تست MFL کابل و آزمون‌های NDT همراه با تقویم دوگانه و پیوست رسمی PDF.',
    'cm.tab_vibration': 'آنالیز ارتعاشات (ISO 20816)',
    'cm.tab_thermography': 'ترموگرافی',
    'cm.tab_oil': 'آنالیز آزمایشگاهی روغن',
    'cm.tab_lubrication': 'مدیریت روانکاری ۴ تجهیز',
    'cm.tab_mfl': 'تست MFL کابل (نشت شار)',
    'cm.tab_ndt': 'آزمون‌های غیرمخرب',

    // CM - 4 Assets
    'cm.eq_motor': 'الکتروموتور اصلی',
    'cm.eq_gearbox': 'گیربکس اصلی',
    'cm.eq_diesel': 'دیزل ژنراتور اضطراری',
    'cm.eq_return_wheel': 'فلکه هرزگرد / برگشت',
    'cm.all_assets': 'همه ۴ تجهیز کلیدی',

    // Vibration ISO 20816
    'cm.iso_20816': 'استاندارد بین‌المللی ISO 20816',
    'cm.zone_a': 'زون A (نوساز / عالی)',
    'cm.zone_b': 'زون B (قابل قبول / مجاز)',
    'cm.zone_c': 'زون C (هشدار / مراقبت)',
    'cm.zone_d': 'زون D (خطر آسیب / توقف)',
    'cm.direction_horizontal': 'افقی (Horizontal - H)',
    'cm.direction_vertical': 'عمودی (Vertical - V)',
    'cm.direction_axial': 'محوری (Axial - A)',
    'cm.velocity': 'سرعت ارتعاشات (Velocity RMS)',
    'cm.acceleration': 'شتاب ارتعاشات (Acceleration)',
    'cm.acc_mode': 'نحوه محاسبه شتاب:',
    'cm.rms': 'RMS (مؤثر)',
    'cm.peak': 'Peak (پیک / اوج)',
    'cm.de_full': 'Drive End (DE) - سمت محرک',
    'cm.nde_full': 'Non-Drive End (NDE) - سمت غیرمحرک / هرزگرد',
    'cm.de_short': 'سمت محرک (DE)',
    'cm.nde_short': 'سمت غیرمحرک (NDE)',
    'cm.fmin': 'فرکانس حداقل (fMin)',
    'cm.fmax': 'فرکانس حداکثر (fMax)',
    'cm.low_freq': 'باند فرکانس پایین (LF)',
    'cm.high_freq': 'باند فرکانس بالا (HF)',
    'cm.locked': '(قفل شده)',
    'cm.matrix_12_title': 'ماتریس ثبت داده‌های ارتعاشی ۱۲ نقطه‌ای (DE و NDE در ۳ راستای A, H, V)',
    'cm.new_vibration_record': 'ثبت اندازه‌گیری جدید ارتعاشات',
    'cm.history_records': 'تاریخچه رکوردهای ارتعاش‌سنجی ۴ تجهیز',
    'cm.max_de_vel': 'حداکثر سرعت DE:',
    'cm.no_tests_yet': 'هنوز تستی برای این تجهیز ثبت نشده است.',
    'cm.zone_a_badge': 'زون A (عالی / مجاز)',
    'cm.zone_b_badge': 'زون B (قابل قبول)',
    'cm.zone_c_badge': 'زون C (هشدار / مراقبت)',
    'cm.zone_d_badge': 'زون D (بحرانی / توقف)',

    // Thermography
    'cm.thermography_title': 'ماژول تخصصی ترموگرافی و تصویربرداری مادون قرمز',
    'cm.thermography_desc': 'پایش دمایی تابلوهای برق PLC، اینورترها، الکتروموتور و لاینرهای رابر فلکه | محاسبه اختلاف دما (ΔT)',
    'cm.new_thermal_record': 'ثبت آزمون ترموگرافی جدید',
    'cm.thermal_history': 'تاریخچه بازرسی‌های ترموگرافی',
    'cm.hotspot_location': 'محل دقیق نقطه داغ',
    'cm.operating_load': 'بار کاری تجهیز حین آزمون',
    'cm.ambient_temp': 'دمای محیط (°C)',
    'cm.max_temp': 'حداکثر دمای ثبت‌شده (°C)',
    'cm.delta_t': 'اختلاف دما با مرجع (ΔT)',
    'cm.severity_normal': 'عادی (ΔT < 10°C)',
    'cm.severity_warning': 'هشدار (10°C ≤ ΔT < 25°C)',
    'cm.severity_critical': 'بحرانی (ΔT ≥ 25°C)',
    'cm.thermal_photo': 'تصویر مادون قرمز (حرارتی)',
    'cm.visual_photo': 'تصویر چشمی (واقعی)',

    // Oil Analysis
    'cm.oil_title': 'ماژول آنالیز آزمایشگاهی روانکارها و روغن',
    'cm.oil_desc': 'پایش عناصر فرسایشی (Fe, Na, PQ, Cu, Pb) بر حسب PPM | ویسکوزیته، عدد اسیدی TAN و کلاس تمیزی ISO 4406',
    'cm.new_oil_record': 'ثبت نتایج آزمایشگاهی جدید روغن',
    'cm.oil_history': 'تاریخچه نتایج آزمایشگاه روغن',
    'cm.lubricant_brand': 'نام تجاری و گرید روغن',
    'cm.fe_label': 'آهن - Fe (PPM)',
    'cm.na_label': 'سدیم - Na (PPM)',
    'cm.pq_label': 'شاخص ذرات آهنی (PQ Index)',
    'cm.cu_label': 'مس - Cu (PPM)',
    'cm.pb_label': 'سرب - Pb (PPM)',
    'cm.viscosity_label': 'ویسکوزیته کینماتیک در 40°C (cSt)',
    'cm.tan_label': 'عدد کل اسیدی TAN (mgKOH/g)',
    'cm.water_ppm_label': 'میزان رطوبت / آب (PPM)',
    'cm.cleanliness_label': 'کلاس تمیزی ذرات (ISO 4406)',
    'cm.oil_cond_normal': 'نرمال و مناسب کاربری (Normal)',
    'cm.oil_cond_warning': 'هشدار و پایش نزدیک (Caution)',
    'cm.oil_cond_critical': 'بحرانی / نیاز به تعویض فوری (Critical)',

    // Lubrication Module
    'cm.lube_title': 'مدیریت و برنامه‌ریزی روانکاری ۴ تجهیز کلیدی',
    'cm.lube_desc': 'پایش مداوم روانکاری موتور، گیربکس، دیزل ژنراتور و چرخ برگشت | تعیین دوره‌ها و مقادیر تزریق',
    'cm.new_lube_record': 'ثبت انجام سرویس روانکاری جدید',
    'cm.lube_history': 'تاریخچه سرویس‌های روانکاری انجام شده',
    'cm.lube_type': 'نوع روانکار',
    'cm.lube_oil_label': 'روغن صنعتی (Oil)',
    'cm.lube_grease_label': 'گریس تخصصی (Grease)',
    'cm.lube_method': 'روش روانکاری',
    'cm.method_gun': 'تزریق با گریس‌پمپ (Grease Gun)',
    'cm.method_topup': 'سرریز و تنظیم سطح (Top-up)',
    'cm.method_drain': 'تخلیه کامل و شارژ مجدد (Drain & Refill)',
    'cm.quantity_unit': 'مقدار و واحد روانکار',
    'cm.interval_hours': 'دوره تناوب ساعت کارکرد',
    'cm.next_scheduled': 'تاریخ سررسید سرویس بعدی',
    'cm.unit_gram': 'گرم (g)',
    'cm.unit_liter': 'لیتر (L)',
    'cm.unit_kg': 'کیلوگرم (kg)',

    // MFL Cable Testing
    'cm.mfl_title': 'ماژول تست نشت شار مغناطیسی کابل (MFL)',
    'cm.mfl_desc': 'پایش عیوب موضعی (LF)، کاهش سطح مقطع فلزی (% LMA) و تعیین دقیق متراژ خرابی طبق استاندارد EN 12927',
    'cm.new_mfl_record': 'ثبت آزمون نشت شار کابل (MFL)',
    'cm.mfl_history': 'سوابق بازرسی‌های مغناطیسی کابل',
    'cm.cable_name': 'نام / شناسه کابل کششی',
    'cm.cable_diameter': 'قطر نامی کابل (mm)',
    'cm.cable_length': 'طول کل کابل (متر)',
    'cm.defect_position': 'موقعیت مکانی عیب از مبدا (متر)',
    'cm.defect_type': 'نوع عیب مغناطیسی',
    'cm.defect_lf': 'LF - شکستگی سیم / گسستگی موضعی (Localized Fault)',
    'cm.defect_lma': 'LMA - کاهش مساحت مقطع فلزی (Loss of Metallic Area)',
    'cm.defect_comp': 'Comp - عیب ترکیبی موضعی و مقطعی (Composite)',
    'cm.lma_percentage': 'درصد کاهش سطح مقطع فلزی (% LMA)',
    'cm.broken_wires': 'تعداد سیم‌های شکسته در طول گام',
    'cm.wires_count': 'سیم',
    'cm.criticality': 'سطح بحرانی بودن عیب (طبق EN 12927)',
    'cm.crit_acceptable': 'قابل قبول / بدون خطر فوری (Acceptable)',
    'cm.crit_warning': 'هشدار و نیاز به بازرسی موضعی (Warning)',
    'cm.crit_serious': 'جدی / بحرانی نیازمند اقدام فوری (Serious)',
    'cm.recommended_action': 'اقدامات پیشنهادی و الزامات استاندارد',

    // NDT Module
    'cm.ndt_title': 'ماژول آزمون‌های غیرمخرب (NDT) اجزای خط',
    'cm.ndt_desc': 'پایش ترک و عیوب ساختاری کلمپ‌ها، هنگرها، شفت فلکه و جوش‌های سازه با متدهای MT, PT, UT, VT, RT',
    'cm.new_ndt_record': 'ثبت بازرسی غیرمخرب (NDT) جدید',
    'cm.ndt_history': 'سوابق آزمون‌های غیرمخرب (NDT)',
    'cm.component_tested': 'قطعه / بخش تحت آزمون',
    'cm.ndt_method': 'روش آزمون غیرمخرب (NDT Method)',
    'cm.standard_applied': 'استاندارد مرجع آزمون (مثلاً EN 1709 / ISO 9712)',
    'cm.inspector_level': 'سطح صلاحیت مفتش NDT',
    'cm.test_result': 'نتیجه ارزیابی آزمون',
    'cm.result_pass': 'مورد تأیید (PASS)',
    'cm.result_fail': 'رد شده / دارای عیب (FAIL)',
    'cm.defect_description': 'شرح عیب، ابعاد و موقعیت ترک یا ناپیوستگی',

    // PDF Uploader & Documents
    'cm.pdf_certificate': 'گواهی و گزارش رسمی بازرسی (PDF)',
    'cm.pdf_select': 'انتخاب فایل گزارش بازرسی (PDF)',
    'cm.pdf_drag_drop': 'یا فایل را اینجا رها کنید',
    'cm.pdf_spec': 'فرمت مجاز: PDF | حداکثر ۲۵ مگابایت | آرشیو خودکار با کد تجهیز و زمان',
    'cm.pdf_uploading': 'در حال آپلود و آرشیو سند در سرور...',
    'cm.pdf_archived': 'آرشیو شده و معتبر در سامانه',
    'cm.pdf_view': 'مشاهده سند',
    'cm.pdf_remove': 'حذف فایل پیوست',
    'cm.attached_report': 'گواهی / گزارش بازرسی پیوست شده (PDF)',

    // Dual Calendar Modal
    'calendar.title': 'انتخاب تاریخ و ساعت انجام بازرسی / تست',
    'calendar.subtitle': 'همگام‌سازی لحظه‌ای تقویم شمسی (جلالی) و میلادی با تبدیل ریاضی دقیق',
    'calendar.set_now': 'اکنون (امروز)',
    'calendar.jalali_tab': 'تقویم خورشیدی (جلالی / شمسی)',
    'calendar.gregorian_tab': 'تقویم میلادی (Gregorian)',
    'calendar.j_year': 'سال شمسی',
    'calendar.j_month': 'ماه شمسی',
    'calendar.j_day': 'روز',
    'calendar.g_year': 'سال میلادی',
    'calendar.g_month': 'ماه میلادی',
    'calendar.g_day': 'روز',
    'calendar.time_title': 'زمان ثبت آزمایش / تست (ساعت و دقیقه)',
    'calendar.hour': 'ساعت',
    'calendar.minute': 'دقیقه',
    'calendar.confirm_btn': 'تأیید تاریخ و زمان',
    'calendar.select_dual_date': 'انتخاب تاریخ شمسی / میلادی',

    // Requests & Approval Workflow
    'nav.requests': 'صندوق درخواست‌ها (تأییدیه)',
    'nav.requests_inbox': 'صندوق درخواست‌ها (تأییدیه)',
    'requests.title': 'پنل مدیریت درخواست‌ها و تأییدیه‌ها',
    'requests.subtitle': 'کارتابل گردش‌کار سلسله‌مراتبی جهت بررسی، ارزیابی مغایرت‌ها (Diff) و تایید یا رد درخواست‌های حذف و ویرایش',
    'requests.pending_count': 'درخواست در انتظار بررسی',
    'requests.filter_all': 'همه درخواست‌ها',
    'requests.filter_pending': 'در انتظار تایید',
    'requests.filter_approved': 'تأیید شده',
    'requests.filter_rejected': 'رد شده',
    'requests.initiator': 'ثبت‌کننده درخواست',
    'requests.action_type': 'نوع عملیات',
    'requests.target': 'موجودیت هدف',
    'requests.rationale': 'علت و ضرورت اقدام',
    'requests.diff_preview': 'پیش‌نمایش تغییرات (Proposed Diff)',
    'requests.before': 'مقدار فعلی / قبل',
    'requests.after': 'مقدار جدید پیشنهادی',
    'requests.escalation_tier': 'سطح ارجاع و بررسی',
    'requests.approve_btn': 'تأیید و اعمال در سیستم',
    'requests.reject_btn': 'رد درخواست',
    'requests.rejection_reason': 'علت رد درخواست',
    'requests.rejection_prompt': 'لطفاً علت رد درخواست را جهت اطلاع متقاضی وارد کنید:',
    'requests.submit_approval_request': 'ارسال درخواست جهت بررسی و تأیید مافوق',
    'requests.approval_required_notice': 'این اقدام محدود بوده و نیازمند تایید سرپرست / مدیر در سلسله‌مراتب سیستم است.',
    'requests.approved_notice': 'درخواست با موفقیت تایید و تغییرات در دیتابیس اعمال گردید.',
    'requests.rejected_notice': 'درخواست رد گردید.',
    'requests.pending_badge': 'در انتظار بررسی',
    'requests.approved_badge': 'تأیید و اعمال شده',
    'requests.rejected_badge': 'رد شده',
    'requests.action_delete': 'حذف',
    'requests.action_edit': 'ویرایش',
    'requests.entity_equipment': 'تجهیز',
    'requests.entity_task': 'دستورکار',
    'requests.entity_station': 'ایستگاه',
    'requests.entity_line': 'خط',
    'requests.rationale_placeholder': 'علت نیاز به این اقدام، شماره مجوز یا توضیحات فنی را ثبت نمایید...',
    'requests.send_request_btn': 'ارسال درخواست به کارتابل مافوق',
    'requests.no_requests': 'هیچ درخواستی در این بخش وجود ندارد.',
    'requests.reviewed_by': 'بررسی شده توسط',
    'requests.rejection_reason_placeholder': 'علت عدم تایید یا دستورات لازم را وارد نمایید...',

    // Multi-tenant Facility Dashboard Metrics & Cover
    'complex.metric_pending_requests': 'درخواست در انتظار',
    'complex.metric_last_inspection': 'آخرین بازرسی مجموعه',
    'complex.metric_last_visit':'آخرین بازدید',
    'complex.view_lines_assets': 'مشاهده و مدیریت خطوط',
    'complex.cover_photo_update': 'ویرایش تصویر کاور مجموعه',
    'complex.cover_photo_restricted': 'دسترسی بارگذاری و ویرایش تصویر مجموعه منحصراً در اختیار مدیر کل یا مدیر این مجموعه می‌باشد.',
    'complex.overview_heading': 'داشبورد نظارتی و پایش مجموعه‌های تله‌کابین',
    'complex.overview_sub': 'پایش متمرکز وضعیت تجهیزات، آخرین بازرسی‌ها و کارتابل تاییدات سلسله‌مراتبی',

    // Qualitative CM Reporting & Analytics
    'nav.cm_qualitative_reports': 'گزارش‌های کیفی CM',
    'cm.qualitative_reports_title': 'گزارش‌های کیفی و تحلیلی پایش وضعیت (CM)',
    'cm.qualitative_reports_subtitle': 'ارزیابی سلامت',
    'cm.executive_report_title': 'گزارش جامع اجرایی سیستم',
    'cm.machine_health_index': 'شاخص جامع سلامت ماشین‌آلات',
    'cm.subdomain_compliance': 'درصد انطباق زیربخش‌های CM',
    'cm.critical_alerts': 'هشدارهای بحرانی و نیاز به اقدام فوری',
    'cm.zone_transitions': 'گذار زون‌های ارتعاشی (ISO 20816)',
    'cm.lma_trend': 'روند کاهش سطح مقطع طناب فولادی (LMA%)',
    'cm.oil_wear_trend': 'روند براده‌های سایشی در روغن (Fe / Cu / Al ppm)',
    'cm.date_range_picker': 'فیلتر بازه زمانی (شمسی / میلادی)',
    'cm.range_last_30': '۳۰ روز اخیر',
    'cm.range_last_90': '۳ ماه اخیر',
    'cm.range_ytd': 'از ابتدای سال',
    'cm.range_all': 'کل سوابق',
    'cm.qualitative_status_distribution': 'توزیع کیفی وضعیت سلامت تجهیزات',
    'cm.domain_vibration': 'آنالیز ارتعاشات',
    'cm.domain_thermography': 'ترموگرافی فروسرخ',
    'cm.domain_oil': 'آنالیز روغن',
    'cm.domain_lubrication': 'پایش روانکاری',
    'cm.domain_mfl': 'تست کابل فولادی (MFL)',
    'cm.domain_ndt': 'آزمون‌های غیرمخرب (NDT)',
    'cm.zone_a': 'زون A (بسیار مطلوب / نو)',
    'cm.zone_b': 'زون B (قابل قبول / کارکرد درازمدت)',
    'cm.zone_c': 'زون C (هشدار / نامناسب برای کارکرد مداوم)',
    'cm.zone_d': 'زون D (خطرناک / احتمال خرابی حتمی)',
    'cm.total_tests': 'تعداد کل بازرسی‌ها و آزمون‌های CM',
    'cm.total_tests_subtitle': 'در بازه زمانی انتخابی در تمامی زیربخش‌های ۶گانه',
    'cm.health_optimal_desc': 'وضعیت بهینه و منطبق بر استانداردهای بازرسی بین‌المللی',
    'cm.health_warning_desc': 'تعدادی تجهیزات نیازمند پایش مجدد یا اقدام اصلاحی می‌باشند',
    'cm.critical_alerts_desc': 'نیازمند مداخله و صدور دستورکار توقف / تعمیر اضطراری',
    'cm.ndt_compliance': 'انطباق آزمون‌های غیرمخرب (NDT Pass)',
    'cm.ndt_compliance_desc': 'مطابق استانداردهای EN 1709 / EN 12927',
    'cm.vibration_trend_title': 'روند تغییرات سرعت ارتعاشات کلی (Velocity RMS mm/s) بر اساس استاندارد ISO 20816',
    'cm.vibration_trend_subtitle': 'خطوط مبنا: زون C (آستانه هشدار ۴.۵ mm/s) و زون D (آستانه بحرانی ۷.۱ mm/s)',
    'cm.mfl_trend_subtitle': 'آستانه هشدار: ۴% تا ۶% | حد خروج از سرویس و اسقاط طناب (Discard Limit): ۸% بر اساس استاندارد ISO 4309',
    'cm.thermography_trend_title': 'روند اختلاف دما (ΔT °C) اتصالات برقی و مکانیکی',
    'cm.thermography_trend_subtitle': 'آستانه اخطار فروسرخ: ΔT > 15°C | آستانه بحرانی تعویض فوری: ΔT > 30°C',
    'cm.qualitative_detail_title': 'گزارش کیفی و تفصیلی',
    'cm.qualitative_detail_desc': 'کلیه آزمایشات با پارامترهای عناصر سایشی (Fe, Cu, Al) و شاخص سلامت ذرات میکرونی در دیتابیس ثبت شده و در قالب گزارش تفصیلی قابل دانلود و پرینت می‌باشد.',

    // Global Unified Search
    'search.global_title': 'جستجوی سراسری سیستم (Unified Search)',
    'search.placeholder': 'جستجو در تجهیزات، بازرسی‌ها، دستورکارها...',
    'search.quick_search': 'جستجوی سریع...',
    'search.badge': 'Ctrl + K',
    'search.input_placeholder': 'جستجو میان تجهیزات، قطعات، بازرسی‌های CM، تست‌های فنی و دستورکارها...',
    'search.category_all': 'همه نتایج',
    'search.category_assets': 'تجهیزات و قطعات',
    'search.category_inspections': 'بازرسی‌ها و CM',
    'search.category_workorders': 'دستورکارها',
    'search.category_requests': 'درخواست‌های تاییدیه',
    'search.no_results': 'هیچ موردی مطابق با عبارت جستجو یافت نشد.',
    'search.quick_tip': 'کلیدهای میانبر: برای باز کردن در هر نقطه کلیدهای Ctrl + K یا Cmd + K را بفشارید.',
    'search.view_item': 'مشاهده در صفحه اختصاصی',
    'search.frequency': 'تناوب',
    'search.standard': 'استاندارد',
    'search.requester': 'متقاضی',
    'search.status': 'وضعیت',
    'search.action_delete': 'درخواست حذف',
    'search.action_edit': 'درخواست ویرایش',
    'search.select_hint': 'انتخاب',
    'search.navigate_hint': 'جابجایی',
    'search.close_hint': 'بستن',
    'search.recent_views': 'دسترسی‌های سریع',
  },
  en: {
    // General & Common
    'app.title': 'Comprehensive Asset Management & CMMS',
    'app.subtitle': 'Ropeway, Cableway & Industrial Equipment Lifecycle, Condition Monitoring & CMMS',
    'common.search': 'Search...',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.cancel': 'Cancel',
    'common.save': 'Save Changes',
    'common.submit': 'Submit Data',
    'common.back': 'Back',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.technician': 'Technician / Specialist',
    'common.inspector': 'Inspector / Authority',
    'common.notes': 'Technical Notes & Observations',
    'common.loading': 'Loading...',
    'common.normal': 'Normal',
    'common.warning': 'Warning',
    'common.danger': 'Danger / Critical',
    'common.acceptable': 'Acceptable',
    'common.all': 'All',
    'common.filter': 'Filter',
    'common.export_pdf': 'Export PDF',
    'common.export_excel': 'Export Excel',
    'common.print': 'Print',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.confirm': 'Confirm',
    'common.change': 'Change',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.yes_delete': 'Yes, Delete',
    'common.select': 'Select',
    'common.details': 'Details & Specifications',
    'common.view': 'View',
    'common.view_new_tab': 'Open in new tab',
    'common.remove': 'Remove',
    'common.no_records_found': 'No records found.',
    'common.showing': 'Showing',
    'common.to': 'to',
    'common.of': 'of',
    'common.records': 'records',
    'common.previous': 'Previous',
    'common.next': 'Next',
    'common.role': 'User Role',
    'common.success': 'Operation completed successfully',
    'common.error': 'An error occurred',
    'common.server_error': 'Server communication error',
    'common.access_denied': 'You do not have permission to view this page.',
    'common.optional': 'Optional',
    'common.required': 'Required',

    // Navigation & Layout
    'nav.stations_equipments': 'Stations & Equipment',
    'nav.analytics': 'Analytics & KPIs',
    'nav.condition_monitoring': 'Condition Monitoring (CM)',
    'nav.lubrication': 'Lubrication Monitoring',
    'nav.downtimes': 'Downtimes Log',
    'nav.admin_section': 'System Administration',
    'nav.users': 'User Management',
    'nav.logs': 'Audit Logs',
    'nav.settings': 'System Settings',
    'nav.profile': 'User Profile',
    'nav.logout': 'Sign Out',
    'nav.switch_complex_line': 'Switch Facility / Line',

    // Hierarchy & Complex Selection
    'complex.default_portal_title': 'Complex Selection & Management Portal',
    'complex.select_instruction': 'Please select the facility / complex you wish to manage.',
    'complex.add_button': 'Add New Complex',
    'complex.name': 'Complex Name',
    'complex.location': 'Location / City',
    'complex.description': 'Complex Description',
    'complex.image_url': 'Complex Image URL',
    'complex.password': 'Access Password (Optional)',
    'complex.enter_password': 'Enter access password for this complex',
    'complex.lines_count': 'Lines Count',
    'complex.no_complexes': 'No complexes found.',
    'complex.edit_complex': 'Edit Complex',
    'complex.placeholder_name': 'e.g. Tochal Cableway / Kish Telecabin Facility',
    'complex.placeholder_loc': 'Tehran, Kish, Ramsar, Chalus...',
    'complex.placeholder_desc': 'Technical specs, altitude, length, and facility details...',
    'complex.placeholder_pass': 'Optional access password...',

    // Line Selection
    'line.add_button': 'Add New Line',
    'line.name': 'Line Name',
    'line.type': 'Line Type',
    'line.stations': 'Stations',
    'line.no_lines': 'No lines registered for this complex.',
    'line.placeholder_name': 'e.g. Line 1 Summit Gondola',
    'line.placeholder_type': 'Gondola, Chairlift, Telesiege, Funicular...',
    'line.telecabin': 'Telecabin / Gondola',
    'line.telesiege': 'Telesiege / Chairlift',
    'line.funicular': 'Funicular Railway',
    'line.gondola': 'Gondola (Detachable)',

    // Stations & Equipment Dashboard
    'dashboard.stations_title': 'Stations of',
    'dashboard.select_station_hint': 'Please select a station to view its equipment and assets.',
    'dashboard.add_station': 'Add New Station',
    'dashboard.station_name': 'Station Name',
    'dashboard.station_sequence': 'Station Sequence No.',
    'dashboard.equipments_title': 'Station Equipment',
    'dashboard.add_equipment': 'Add New Equipment',
    'dashboard.equipment_name': 'Equipment Name',
    'dashboard.equipment_code': 'Equipment Code',
    'dashboard.import_excel': 'Import Excel Tasks',
    'dashboard.select_standard_for_import': 'Select Reference Manufacturer Standard for Imported File:',
    'dashboard.standard_bartholet': 'Bartholet Standard',
    'dashboard.standard_doppelmayr': 'Doppelmayr Standard',
    'dashboard.standard_poma': 'Poma Standard',
    'dashboard.standard_general': 'General / Auto-Detect File Standard',
    'dashboard.standard_given': 'Given Standard / General (ISO / Custom)',
    'dashboard.all_standards': 'All Standards',
    'dashboard.no_equipments': 'No equipment registered for this station.',
    'dashboard.excel_modal_desc': 'Import maintenance tasks and equipment categorized by Bartholet, Doppelmayr, Poma, or General standards.',
    'dashboard.excel_select_file': 'Excel File (.xlsx, .xls):',
    'dashboard.import_submit': 'Upload & Process Data',
    'dashboard.importing': 'Processing spreadsheet...',
    'dashboard.reorder': 'Reorder Display Order',

    // Equipment Detail & Tasks
    'equipment.details': 'Equipment Details',
    'equipment.tasks': 'Maintenance & Inspection Tasks',
    'equipment.add_task': 'Add Task',
    'equipment.task_subject': 'Task Subject',
    'equipment.task_code': 'Task Code',
    'equipment.task_standard': 'Manufacturer Standard',
    'equipment.sort_by_standard': 'Sort by Standard:',
    'equipment.frequency': 'Frequency',
    'equipment.last_date': 'Last Inspection',
    'equipment.next_date': 'Next Due Date',
    'equipment.instructions': 'Instructions',
    'equipment.criteria': 'Acceptance Criteria',
    'equipment.part_name': 'Part / Component Name',
    'equipment.warning': 'Safety Warning & Notice',
    'equipment.inspect_action': 'Log Inspection',
    'equipment.operating_hours': 'Operating Hours',
    'equipment.inspection_comment': 'Inspection Remarks & Log',
    'equipment.status_normal': 'Normal',
    'equipment.status_warning': 'Warning',
    'equipment.status_broken': 'Broken / Needs Repair',
    'equipment.freq_daily': 'Daily',
    'equipment.freq_weekly': 'Weekly',
    'equipment.freq_monthly': 'Monthly',
    'equipment.freq_3months': '3 Months',
    'equipment.freq_6months': '6 Months',
    'equipment.freq_annually': 'Annually',
    'equipment.history': 'Historical Inspection Logs',

    // Downtimes & Management
    'downtime.title': 'Downtimes Management & Root Cause Tracking',
    'downtime.subtitle': 'Failure analysis, repair times, and cableway availability metrics',
    'downtime.add_new': 'Log New Downtime',
    'downtime.equipment': 'Affected Asset / Equipment',
    'downtime.reason': 'Failure Cause',
    'downtime.start_time': 'Start Time',
    'downtime.duration': 'Duration',
    'downtime.duration_min': 'Duration (Minutes)',
    'downtime.entire_site': 'Entire Facility / Site',
    'downtime.unknown': 'Unspecified',
    'downtime.delete_title': 'Delete Downtime Record',
    'downtime.delete_confirm': 'Are you sure you want to delete this downtime report?',
    'downtime.reason_mechanical': 'Mechanical Fault',
    'downtime.reason_electrical': 'Electrical / Inverter Fault',
    'downtime.reason_weather': 'Severe Weather / High Wind',
    'downtime.reason_human': 'Operator / Human Error',
    'downtime.reason_pm': 'Preventive Maintenance',
    'downtime.reason_other': 'Other Causes',
    'downtime.modal_title': 'Log New Downtime Incident',
    'downtime.all_equipment_option': 'Entire Line / All Equipment',

    // Analytics & KPIs
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Statistical breakdown of preventive maintenance, reliability, and outages',
    'analytics.total_tasks': 'Total Annual Tasks',
    'analytics.reliability': 'Reliability Rate (Estimated)',
    'analytics.total_downtimes': 'Total Downtime (Minutes)',
    'analytics.compliance_title': 'Maintenance Task Compliance Rate',
    'analytics.breakdown_title': 'Root Causes of Line Downtimes',
    'analytics.on_time': 'Completed (On-time)',
    'analytics.delayed': 'Delayed',
    'analytics.pending': 'Pending / Overdue',
    'analytics.no_data': 'No data available for chart rendering',
    'analytics.generating_pdf': 'Generating PDF document...',
    'analytics.export_btn': 'Export PDF / Print Report',

    // Users & Roles
    'users.title': 'User Management & Permissions',
    'users.subtitle': 'Role definitions, security policies, and facility/line user assignments',
    'users.add_user': 'Add New User',
    'users.full_name': 'Full Name',
    'users.username': 'Username',
    'users.password': 'Password',
    'users.phone': 'Phone Number',
    'users.position': 'Position / Title',
    'users.role': 'System Role & Access',
    'users.assigned_complex': 'Assigned Facility',
    'users.assigned_line': 'Assigned Line',
    'users.assigned_station': 'Assigned Station',
    'users.role_super_admin': 'Super Administrator',
    'users.role_complex_admin': 'Complex Administrator',
    'users.role_line_supervisor': 'Line Supervisor',
    'users.role_station_operator': 'Station Operator',
    'users.role_manager': 'System Manager',
    'users.role_operator': 'Technical Operator',
    'users.delete_confirm': 'Are you sure you want to delete this user account?',
    'users.no_users': 'No registered users found.',

    // Logs
    'logs.title': 'Audit Logs & Security Events',
    'logs.subtitle': 'Complete history of logins, system modifications, and user transactions',
    'logs.user': 'User',
    'logs.action': 'Action',
    'logs.details': 'Details & Payload',
    'logs.timestamp': 'Timestamp (Date & Time)',
    'logs.loading': 'Fetching activity logs...',
    'logs.filename': 'System_Audit_Logs',
    'logs.search_placeholder': 'Search user, action, details...',

    // Settings
    'settings.title': 'System Settings & Branding',
    'settings.subtitle': 'Manage company branding, system title, and enterprise logo',
    'settings.company_name': 'System / Organization Name',
    'settings.logo': 'System Logo',
    'settings.change_logo': 'Change Company Logo',
    'settings.no_logo': 'No Logo',
    'settings.save_settings': 'Save Settings',
    'settings.saved_success': 'Settings successfully saved and updated.',
    'settings.placeholder_company': 'e.g. Tochal Cableway Enterprise CMMS',

    // Profile
    'profile.title': 'User Profile & Preferences',
    'profile.subtitle': 'View and update your personal credentials and access password',
    'profile.new_password': 'New Password',
    'profile.new_password_hint': 'Leave blank if you do not wish to change your password',
    'profile.senior_manager': 'Senior Manager',
    'profile.operator': 'System Operator',

    // Login
    'login.title': 'CMMS & Condition Monitoring System',
    'login.subtitle': 'Sign in to access condition monitoring, maintenance & telemetry',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.logging_in': 'Authenticating...',
    'login.secure_note': 'Secure CMMS Portal • All system interactions are audited',
    'login.invalid_creds': 'Invalid username or password.',

    // Condition Monitoring (CM) - Core
    'cm.title': 'Comprehensive Condition Monitoring (CM)',
    'cm.subtitle': 'End-to-end monitoring across 6 critical domains: ISO 20816 Vibration, Thermography, Oil Analysis, Lubrication, MFL Cable Testing, and NDT with dual calendar and PDF archival.',
    'cm.tab_vibration': 'Vibration Analysis (ISO 20816)',
    'cm.tab_thermography': 'Thermography (Thermal Scan)',
    'cm.tab_oil': 'Oil Laboratory Analysis',
    'cm.tab_lubrication': 'Lubrication Management',
    'cm.tab_mfl': 'MFL Cable Testing',
    'cm.tab_ndt': 'Non-Destructive Testing (NDT)',

    // CM - 4 Assets
    'cm.eq_motor': 'Main Electric Motor',
    'cm.eq_gearbox': 'Main Gearbox',
    'cm.eq_diesel': 'Emergency Diesel Gen',
    'cm.eq_return_wheel': 'Return Sheave / Bullwheel',
    'cm.all_assets': 'All 4 Key Assets',

    // Vibration ISO 20816
    'cm.iso_20816': 'International Standard ISO 20816',
    'cm.zone_a': 'Zone A (Newly Commissioned / Good)',
    'cm.zone_b': 'Zone B (Unrestricted / Acceptable)',
    'cm.zone_c': 'Zone C (Restricted / Warning)',
    'cm.zone_d': 'Zone D (Damage Risk / Immediate Action)',
    'cm.direction_horizontal': 'Horizontal (H)',
    'cm.direction_vertical': 'Vertical (V)',
    'cm.direction_axial': 'Axial (A)',
    'cm.velocity': 'Vibration Velocity (RMS mm/s)',
    'cm.acceleration': 'Vibration Acceleration',
    'cm.acc_mode': 'Acceleration Mode:',
    'cm.rms': 'RMS',
    'cm.peak': 'Peak',
    'cm.de_full': 'Drive End (DE) - Drive Side',
    'cm.nde_full': 'Non-Drive End (NDE) - Non-Drive Side',
    'cm.de_short': 'Drive End (DE)',
    'cm.nde_short': 'Non-Drive End (NDE)',
    'cm.fmin': 'Minimum Frequency (fMin)',
    'cm.fmax': 'Maximum Frequency (fMax)',
    'cm.low_freq': 'Low-Frequency Band (LF)',
    'cm.high_freq': 'High-Frequency Band (HF)',
    'cm.locked': '(Locked)',
    'cm.matrix_12_title': '12-Input DE & NDE Vibration Grid Matrix (Axial, Horizontal, Vertical)',
    'cm.new_vibration_record': 'Record New Vibration Test',
    'cm.history_records': 'Vibration Test Records History (4 Core Assets)',
    'cm.max_de_vel': 'Max DE Vel:',
    'cm.no_tests_yet': 'No vibration tests recorded yet for this asset.',
    'cm.zone_a_badge': 'Zone A (Good)',
    'cm.zone_b_badge': 'Zone B (Acceptable)',
    'cm.zone_c_badge': 'Zone C (Warning)',
    'cm.zone_d_badge': 'Zone D (Critical)',

    // Thermography
    'cm.thermography_title': 'Thermography & Infrared Thermal Scan',
    'cm.thermography_desc': 'Thermal imaging of PLC panels, inverters, motors, and sheave rubber liners | Hotspot differential (ΔT) analysis',
    'cm.new_thermal_record': 'Record New Thermal Scan',
    'cm.thermal_history': 'Thermographic Inspection Records',
    'cm.hotspot_location': 'Exact Hotspot Location',
    'cm.operating_load': 'Operating Load During Inspection',
    'cm.ambient_temp': 'Ambient Temp (°C)',
    'cm.max_temp': 'Maximum Registered Temp (°C)',
    'cm.delta_t': 'Temperature Differential (ΔT °C)',
    'cm.severity_normal': 'Normal (ΔT < 10°C)',
    'cm.severity_warning': 'Warning (10°C ≤ ΔT < 25°C)',
    'cm.severity_critical': 'Critical (ΔT ≥ 25°C)',
    'cm.thermal_photo': 'Infrared (Thermal) Photo',
    'cm.visual_photo': 'Visual (Optical) Photo',

    // Oil Analysis
    'cm.oil_title': 'Oil & Lubricant Laboratory Analysis',
    'cm.oil_desc': 'Wear debris elements (Fe, Na, PQ, Cu, Pb) in PPM | Kinematic viscosity at 40°C, TAN, and ISO 4406 cleanliness',
    'cm.new_oil_record': 'Record New Oil Lab Certificate',
    'cm.oil_history': 'Oil Analysis Laboratory History',
    'cm.lubricant_brand': 'Lubricant Brand & ISO VG Grade',
    'cm.fe_label': 'Iron - Fe (PPM)',
    'cm.na_label': 'Sodium - Na (PPM)',
    'cm.pq_label': 'PQ Ferrous Index',
    'cm.cu_label': 'Copper - Cu (PPM)',
    'cm.pb_label': 'Lead - Pb (PPM)',
    'cm.viscosity_label': 'Kinematic Viscosity at 40°C (cSt)',
    'cm.tan_label': 'Total Acid Number TAN (mgKOH/g)',
    'cm.water_ppm_label': 'Water Content (PPM)',
    'cm.cleanliness_label': 'ISO 4406 Cleanliness Code',
    'cm.oil_cond_normal': 'Normal / Fit for Service',
    'cm.oil_cond_warning': 'Caution / Monitor Closely',
    'cm.oil_cond_critical': 'Critical / Immediate Change Required',

    // Lubrication Module
    'cm.lube_title': 'Lubrication Management & Scheduling (4 Key Assets)',
    'cm.lube_desc': 'Continuous tracking of grease and oil replenishments for Motor, Gearbox, Diesel Gen, and Return Bullwheel',
    'cm.new_lube_record': 'Record New Lubrication Service',
    'cm.lube_history': 'Lubrication History & Maintenance Logs',
    'cm.lube_type': 'Lubricant Type',
    'cm.lube_oil_label': 'Industrial Oil',
    'cm.lube_grease_label': 'Specialty Grease',
    'cm.lube_method': 'Replenishment Method',
    'cm.method_gun': 'Grease Gun Injection',
    'cm.method_topup': 'Top-up to Sightglass Level',
    'cm.method_drain': 'Full Drain & Refill',
    'cm.quantity_unit': 'Quantity & Unit',
    'cm.interval_hours': 'Operating Interval (Hours)',
    'cm.next_scheduled': 'Next Scheduled Date',
    'cm.unit_gram': 'Grams (g)',
    'cm.unit_liter': 'Liters (L)',
    'cm.unit_kg': 'Kilograms (kg)',

    // MFL Cable Testing
    'cm.mfl_title': 'Magnetic Flux Leakage (MFL) Cable Testing',
    'cm.mfl_desc': 'Localized faults (LF), loss of metallic area (% LMA), and defect location mapping according to EN 12927',
    'cm.new_mfl_record': 'Record New MFL Cable Test',
    'cm.mfl_history': 'Historical MFL Inspection Logs',
    'cm.cable_name': 'Haul Rope / Cable Designation',
    'cm.cable_diameter': 'Nominal Rope Diameter (mm)',
    'cm.cable_length': 'Total Rope Length (m)',
    'cm.defect_position': 'Defect Position from Zero Point (m)',
    'cm.defect_type': 'Magnetic Defect Type',
    'cm.defect_lf': 'LF - Localized Fault / Broken Wire',
    'cm.defect_lma': 'LMA - Loss of Metallic Area',
    'cm.defect_comp': 'Comp - Composite Fault (LF + LMA)',
    'cm.lma_percentage': 'Metallic Cross-Section Reduction (% LMA)',
    'cm.broken_wires': 'Broken Wires Count in Lay Length',
    'cm.wires_count': 'wires',
    'cm.criticality': 'Criticality Level (EN 12927)',
    'cm.crit_acceptable': 'Acceptable / No Immediate Hazard',
    'cm.crit_warning': 'Warning / Local Visual Check Required',
    'cm.crit_serious': 'Serious / Urgent Corrective Action Required',
    'cm.recommended_action': 'Recommended Technical Actions',

    // NDT Module
    'cm.ndt_title': 'Non-Destructive Testing (NDT) Module',
    'cm.ndt_desc': 'Structural flaw & fatigue crack detection on grips, hangers, bullwheel shafts, and structural welds (MT, PT, UT, VT, RT)',
    'cm.new_ndt_record': 'Record New NDT Inspection',
    'cm.ndt_history': 'Historical NDT Inspection Certificates',
    'cm.component_tested': 'Inspected Component / Part',
    'cm.ndt_method': 'NDT Method (MT, PT, UT, VT, RT)',
    'cm.standard_applied': 'Governing Standard (e.g. EN 1709 / ISO 9712)',
    'cm.inspector_level': 'NDT Inspector Qualification Level',
    'cm.test_result': 'Evaluation Result',
    'cm.result_pass': 'PASS (Conforming)',
    'cm.result_fail': 'FAIL (Defect Detected)',
    'cm.defect_description': 'Defect Indications, Dimensions & Location',

    // PDF Uploader & Documents
    'cm.pdf_certificate': 'Official Inspection Certificate (PDF)',
    'cm.pdf_select': 'Select Inspection Report (PDF)',
    'cm.pdf_drag_drop': 'or drag and drop document here',
    'cm.pdf_spec': 'Accepted format: PDF | Max 25 MB | Automatically archived with equipment ID and timestamp',
    'cm.pdf_uploading': 'Uploading & indexing document in repository...',
    'cm.pdf_archived': 'Archived & Verified in System',
    'cm.pdf_view': 'View Document',
    'cm.pdf_remove': 'Remove PDF',
    'cm.attached_report': 'Attached Official Report / Certificate (PDF)',

    // Dual Calendar Modal
    'calendar.title': 'Select Inspection Date & Time',
    'calendar.subtitle': 'Instant synchronization between Jalali (Solar) and Gregorian calendars with exact conversion',
    'calendar.set_now': 'Set to Now',
    'calendar.jalali_tab': 'Jalali (Persian Calendar)',
    'calendar.gregorian_tab': 'Gregorian Calendar',
    'calendar.j_year': 'Jalali Year',
    'calendar.j_month': 'Jalali Month',
    'calendar.j_day': 'Day',
    'calendar.g_year': 'Gregorian Year',
    'calendar.g_month': 'Gregorian Month',
    'calendar.g_day': 'Day',
    'calendar.time_title': 'Test Timestamp (Hours & Minutes)',
    'calendar.hour': 'Hour',
    'calendar.minute': 'Minute',
    'calendar.confirm_btn': 'Confirm Date & Time',
    'calendar.select_dual_date': 'Select Date (Dual Calendar)',

    // Requests & Approval Workflow
    'nav.requests': 'Requests Inbox',
    'nav.requests_inbox': 'Requests Inbox',
    'requests.title': 'Approval Requests Inbox',
    'requests.subtitle': 'Hierarchical workflow approval inbox to review, inspect proposed diffs, and approve or reject restricted actions',
    'requests.pending_count': 'pending approval requests',
    'requests.filter_all': 'All Requests',
    'requests.filter_pending': 'Pending',
    'requests.filter_approved': 'Approved',
    'requests.filter_rejected': 'Rejected',
    'requests.initiator': 'Initiator',
    'requests.action_type': 'Action Type',
    'requests.target': 'Target Entity',
    'requests.rationale': 'Rationale / Reason',
    'requests.diff_preview': 'Proposed Changes Diff',
    'requests.before': 'Current / Before',
    'requests.after': 'Proposed / After',
    'requests.escalation_tier': 'Escalation Tier',
    'requests.approve_btn': 'Approve & Execute',
    'requests.reject_btn': 'Reject Request',
    'requests.rejection_reason': 'Rejection Reason',
    'requests.rejection_prompt': 'Please enter the reason for rejection:',
    'requests.submit_approval_request': 'Submit for Hierarchical Approval',
    'requests.approval_required_notice': 'This restricted action requires approval from a superior role in the chain of command.',
    'requests.approved_notice': 'Request approved successfully and applied to database.',
    'requests.rejected_notice': 'Request was rejected.',
    'requests.pending_badge': 'Pending Review',
    'requests.approved_badge': 'Approved & Applied',
    'requests.rejected_badge': 'Rejected',
    'requests.action_delete': 'Delete',
    'requests.action_edit': 'Edit',
    'requests.entity_equipment': 'Equipment',
    'requests.entity_task': 'Task / Work Order',
    'requests.entity_station': 'Station',
    'requests.entity_line': 'Line',
    'requests.rationale_placeholder': 'Enter justification, work permit number, or technical rationale...',
    'requests.send_request_btn': 'Send Request to Superior Inbox',
    'requests.no_requests': 'No requests found in this section.',
    'requests.reviewed_by': 'Reviewed by',
    'requests.rejection_reason_placeholder': 'Enter the reason for rejection or instructions...',

    // Multi-tenant Facility Dashboard Metrics & Cover
    'complex.metric_pending_requests': 'Pending Requests',
    'complex.metric_last_inspection': 'Last Facility Inspection',
    'complex.metric_last_visit': 'Last Visit / Audit',
    'complex.view_lines_assets': 'View Lines & Assets',
    'complex.cover_photo_update': 'Update Cover Image',
    'complex.cover_photo_restricted': 'Cover photo editing is strictly restricted to the Facility Manager and General Manager.',
    'complex.overview_heading': 'Ropeway Facilities Monitoring Dashboard',
    'complex.overview_sub': 'Centralized monitoring of assets, latest inspections, and hierarchical approval workflows',

    // Qualitative CM Reporting & Analytics
    'nav.cm_qualitative_reports': 'Qualitative CM Reports',
    'cm.qualitative_reports_title': 'Qualitative Condition Monitoring (CM) Reports',
    'cm.qualitative_reports_subtitle': 'Sub-domain health evaluations, qualitative trends, ISO 20816 vibration zones, and unified machinery health index',
    'cm.executive_report_title': 'Executive Comprehensive CM Report',
    'cm.machine_health_index': 'Machine Health Index (MHI)',
    'cm.subdomain_compliance': 'CM Sub-domain Compliance',
    'cm.critical_alerts': 'Critical Active Alerts',
    'cm.zone_transitions': 'Vibration Zone Transitions (ISO 20816)',
    'cm.lma_trend': 'Steel Wire Rope LMA% Trends (MFL)',
    'cm.oil_wear_trend': 'Oil Wear Metals Trend (Fe / Cu / Al ppm)',
    'cm.date_range_picker': 'Date Range Filter (Jalali / Gregorian)',
    'cm.range_last_30': 'Last 30 Days',
    'cm.range_last_90': 'Last 90 Days',
    'cm.range_ytd': 'Year to Date',
    'cm.range_all': 'All History',
    'cm.qualitative_status_distribution': 'Qualitative Asset Health Distribution',
    'cm.domain_vibration': 'Vibration Analysis',
    'cm.domain_thermography': 'Infrared Thermography',
    'cm.domain_oil': 'Oil Analysis',
    'cm.domain_lubrication': 'Lubrication Management',
    'cm.domain_mfl': 'MFL Wire Rope Testing',
    'cm.domain_ndt': 'Non-Destructive Testing (NDT)',
    'cm.zone_a': 'Zone A (Good / Newly Commissioned)',
    'cm.zone_b': 'Zone B (Acceptable / Long-term operation)',
    'cm.zone_c': 'Zone C (Warning / Unsatisfactory for continuous running)',
    'cm.zone_d': 'Zone D (Danger / Critical fault)',
    'cm.total_tests': 'Total CM Inspections & Tests',
    'cm.total_tests_subtitle': 'In the selected timeframe across all 6 subdomains',
    'cm.health_optimal_desc': 'Optimal condition conforming to international inspection standards',
    'cm.health_warning_desc': 'Some equipment requires re-monitoring or corrective action',
    'cm.critical_alerts_desc': 'Requires intervention & emergency shutdown / repair order',
    'cm.ndt_compliance': 'Non-Destructive Testing Compliance (NDT Pass)',
    'cm.ndt_compliance_desc': 'Conforming to EN 1709 / EN 12927 standards',
    'cm.vibration_trend_title': 'Overall Vibration Velocity Trend (Velocity RMS mm/s) - ISO 20816 Standard',
    'cm.vibration_trend_subtitle': 'Baseline thresholds: Zone C (Warning: 4.5 mm/s) & Zone D (Danger: 7.1 mm/s)',
    'cm.mfl_trend_subtitle': 'Warning threshold: 4% to 6% | Discard limit: 8% according to ISO 4309',
    'cm.thermography_trend_title': 'Temperature Differential (ΔT °C) Trend - Electrical & Mechanical',
    'cm.thermography_trend_subtitle': 'Infrared Warning threshold: ΔT > 15°C | Immediate Replacement Critical: ΔT > 30°C',
    'cm.qualitative_detail_title': 'Detailed Qualitative Report',
    'cm.qualitative_detail_desc': 'All tests with wear elemental parameters (Fe, Cu, Al) and microscopic particle health indices are recorded and available for detailed reporting & printing.',

    // Global Unified Search
    'search.global_title': 'Unified Global Search',
    'search.placeholder': 'Search assets, inspections, work orders...',
    'search.quick_search': 'Quick search...',
    'search.badge': '⌘K',
    'search.input_placeholder': 'Search across assets, CM diagnostics, technical tests, work orders...',
    'search.category_all': 'All Categories',
    'search.category_assets': 'Assets & Components',
    'search.category_inspections': 'Inspections & CM',
    'search.category_workorders': 'Work Orders',
    'search.category_requests': 'Approval Requests',
    'search.no_results': 'No matching records found.',
    'search.quick_tip': 'Keyboard shortcut: Press Ctrl + K or Cmd + K anywhere to open search.',
    'search.view_item': 'View item',
    'search.frequency': 'Frequency',
    'search.standard': 'Standard',
    'search.requester': 'Requester',
    'search.status': 'Status',
    'search.action_delete': 'Delete Request',
    'search.action_edit': 'Edit Request',
    'search.select_hint': 'Select',
    'search.navigate_hint': 'Navigate',
    'search.close_hint': 'Close',
    'search.recent_views': 'Quick Access',
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'fa',
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key: string, def?: string) => def || key,
  isRtl: true,
  formatDate: (j?: string, g?: string) => j || g || '',
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('app_lang') as Language) || 'fa';
  });

  const isRtl = language === 'fa';

  useEffect(() => {
    localStorage.setItem('app_lang', language);
    document.documentElement.setAttribute('dir', isRtl ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', language);
    if (document.body) {
      document.body.setAttribute('dir', isRtl ? 'rtl' : 'ltr');
    }
  }, [language, isRtl]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const toggleLanguage = () => {
    setLanguageState((prev) => (prev === 'fa' ? 'en' : 'fa'));
  };

  const t = (key: string, defaultText?: string): string => {
    const text = translations[language]?.[key];
    if (text !== undefined) return text;
    // Fallback to FA if in EN and missing, or default
    return translations.fa?.[key] || defaultText || key;
  };

  const formatDate = (jalaliStr?: string, gregorianStr?: string): string => {
    if (!isRtl && gregorianStr) return gregorianStr;
    if (jalaliStr) return jalaliStr;
    return gregorianStr || '';
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, isRtl, formatDate }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
